-- Shamba Track — Seed: world currencies (ISO 4217)
-- Farmer selects one at farm setup; searchable by name/country/code in UI.

INSERT INTO currencies (code, name, symbol, country) VALUES
('AED', 'UAE Dirham', 'د.إ', 'United Arab Emirates'),
('AFN', 'Afghani', '؋', 'Afghanistan'),
('ALL', 'Lek', 'L', 'Albania'),
('AMD', 'Armenian Dram', '֏', 'Armenia'),
('ANG', 'Netherlands Antillean Guilder', 'ƒ', 'Curaçao / Sint Maarten'),
('AOA', 'Kwanza', 'Kz', 'Angola'),
('ARS', 'Argentine Peso', '$', 'Argentina'),
('AUD', 'Australian Dollar', 'A$', 'Australia'),
('AWG', 'Aruban Florin', 'ƒ', 'Aruba'),
('AZN', 'Azerbaijani Manat', '₼', 'Azerbaijan'),
('BAM', 'Convertible Mark', 'KM', 'Bosnia and Herzegovina'),
('BBD', 'Barbados Dollar', '$', 'Barbados'),
('BDT', 'Taka', '৳', 'Bangladesh'),
('BGN', 'Bulgarian Lev', 'лв', 'Bulgaria'),
('BHD', 'Bahraini Dinar', '.د.ب', 'Bahrain'),
('BIF', 'Burundi Franc', 'FBu', 'Burundi'),
('BMD', 'Bermudian Dollar', '$', 'Bermuda'),
('BND', 'Brunei Dollar', '$', 'Brunei'),
('BOB', 'Boliviano', 'Bs.', 'Bolivia'),
('BRL', 'Brazilian Real', 'R$', 'Brazil'),
('BSD', 'Bahamian Dollar', '$', 'Bahamas'),
('BTN', 'Ngultrum', 'Nu.', 'Bhutan'),
('BWP', 'Pula', 'P', 'Botswana'),
('BYN', 'Belarusian Ruble', 'Br', 'Belarus'),
('BZD', 'Belize Dollar', 'BZ$', 'Belize'),
('CAD', 'Canadian Dollar', 'C$', 'Canada'),
('CDF', 'Congolese Franc', 'FC', 'Congo (DRC)'),
('CHF', 'Swiss Franc', 'CHF', 'Switzerland'),
('CLP', 'Chilean Peso', '$', 'Chile'),
('CNY', 'Yuan Renminbi', '¥', 'China'),
('COP', 'Colombian Peso', '$', 'Colombia'),
('CRC', 'Costa Rican Colon', '₡', 'Costa Rica'),
('CUP', 'Cuban Peso', '$', 'Cuba'),
('CVE', 'Cabo Verde Escudo', '$', 'Cabo Verde'),
('CZK', 'Czech Koruna', 'Kč', 'Czechia'),
('DJF', 'Djibouti Franc', 'Fdj', 'Djibouti'),
('DKK', 'Danish Krone', 'kr', 'Denmark'),
('DOP', 'Dominican Peso', 'RD$', 'Dominican Republic'),
('DZD', 'Algerian Dinar', 'دج', 'Algeria'),
('EGP', 'Egyptian Pound', '£', 'Egypt'),
('ERN', 'Nakfa', 'Nfk', 'Eritrea'),
('ETB', 'Ethiopian Birr', 'Br', 'Ethiopia'),
('EUR', 'Euro', '€', 'Eurozone'),
('FJD', 'Fiji Dollar', '$', 'Fiji'),
('FKP', 'Falkland Islands Pound', '£', 'Falkland Islands'),
('GBP', 'Pound Sterling', '£', 'United Kingdom'),
('GEL', 'Lari', '₾', 'Georgia'),
('GHS', 'Ghana Cedi', '₵', 'Ghana'),
('GIP', 'Gibraltar Pound', '£', 'Gibraltar'),
('GMD', 'Dalasi', 'D', 'Gambia'),
('GNF', 'Guinean Franc', 'FG', 'Guinea'),
('GTQ', 'Quetzal', 'Q', 'Guatemala'),
('GYD', 'Guyana Dollar', '$', 'Guyana'),
('HKD', 'Hong Kong Dollar', 'HK$', 'Hong Kong'),
('HNL', 'Lempira', 'L', 'Honduras'),
('HTG', 'Gourde', 'G', 'Haiti'),
('HUF', 'Forint', 'Ft', 'Hungary'),
('IDR', 'Rupiah', 'Rp', 'Indonesia'),
('ILS', 'New Israeli Sheqel', '₪', 'Israel'),
('INR', 'Indian Rupee', '₹', 'India'),
('IQD', 'Iraqi Dinar', 'ع.د', 'Iraq'),
('IRR', 'Iranian Rial', '﷼', 'Iran'),
('ISK', 'Iceland Krona', 'kr', 'Iceland'),
('JMD', 'Jamaican Dollar', 'J$', 'Jamaica'),
('JOD', 'Jordanian Dinar', 'د.ا', 'Jordan'),
('JPY', 'Yen', '¥', 'Japan'),
('KES', 'Kenyan Shilling', 'KSh', 'Kenya'),
('KGS', 'Som', 'с', 'Kyrgyzstan'),
('KHR', 'Riel', '៛', 'Cambodia'),
('KMF', 'Comorian Franc', 'CF', 'Comoros'),
('KPW', 'North Korean Won', '₩', 'North Korea'),
('KRW', 'Won', '₩', 'South Korea'),
('KWD', 'Kuwaiti Dinar', 'د.ك', 'Kuwait'),
('KYD', 'Cayman Islands Dollar', '$', 'Cayman Islands'),
('KZT', 'Tenge', '₸', 'Kazakhstan'),
('LAK', 'Lao Kip', '₭', 'Laos'),
('LBP', 'Lebanese Pound', 'ل.ل', 'Lebanon'),
('LKR', 'Sri Lanka Rupee', 'Rs', 'Sri Lanka'),
('LRD', 'Liberian Dollar', '$', 'Liberia'),
('LSL', 'Loti', 'L', 'Lesotho'),
('LYD', 'Libyan Dinar', 'ل.د', 'Libya'),
('MAD', 'Moroccan Dirham', 'د.م.', 'Morocco'),
('MDL', 'Moldovan Leu', 'L', 'Moldova'),
('MGA', 'Malagasy Ariary', 'Ar', 'Madagascar'),
('MKD', 'Denar', 'ден', 'North Macedonia'),
('MMK', 'Kyat', 'K', 'Myanmar'),
('MNT', 'Tugrik', '₮', 'Mongolia'),
('MOP', 'Pataca', 'MOP$', 'Macao'),
('MRU', 'Ouguiya', 'UM', 'Mauritania'),
('MUR', 'Mauritius Rupee', '₨', 'Mauritius'),
('MVR', 'Rufiyaa', '.ރ', 'Maldives'),
('MWK', 'Malawi Kwacha', 'MK', 'Malawi'),
('MXN', 'Mexican Peso', '$', 'Mexico'),
('MYR', 'Malaysian Ringgit', 'RM', 'Malaysia'),
('MZN', 'Mozambique Metical', 'MT', 'Mozambique'),
('NAD', 'Namibia Dollar', '$', 'Namibia'),
('NGN', 'Naira', '₦', 'Nigeria'),
('NIO', 'Cordoba Oro', 'C$', 'Nicaragua'),
('NOK', 'Norwegian Krone', 'kr', 'Norway'),
('NPR', 'Nepalese Rupee', '₨', 'Nepal'),
('NZD', 'New Zealand Dollar', '$', 'New Zealand'),
('OMR', 'Rial Omani', 'ر.ع.', 'Oman'),
('PAB', 'Balboa', 'B/.', 'Panama'),
('PEN', 'Sol', 'S/', 'Peru'),
('PGK', 'Kina', 'K', 'Papua New Guinea'),
('PHP', 'Philippine Peso', '₱', 'Philippines'),
('PKR', 'Pakistan Rupee', '₨', 'Pakistan'),
('PLN', 'Zloty', 'zł', 'Poland'),
('PYG', 'Guarani', '₲', 'Paraguay'),
('QAR', 'Qatari Rial', 'ر.ق', 'Qatar'),
('RON', 'Romanian Leu', 'lei', 'Romania'),
('RSD', 'Serbian Dinar', 'дин.', 'Serbia'),
('RUB', 'Russian Ruble', '₽', 'Russia'),
('RWF', 'Rwanda Franc', 'FRw', 'Rwanda'),
('SAR', 'Saudi Riyal', 'ر.س', 'Saudi Arabia'),
('SBD', 'Solomon Islands Dollar', '$', 'Solomon Islands'),
('SCR', 'Seychelles Rupee', '₨', 'Seychelles'),
('SDG', 'Sudanese Pound', 'ج.س.', 'Sudan'),
('SEK', 'Swedish Krona', 'kr', 'Sweden'),
('SGD', 'Singapore Dollar', 'S$', 'Singapore'),
('SHP', 'Saint Helena Pound', '£', 'Saint Helena'),
('SLE', 'Leone', 'Le', 'Sierra Leone'),
('SOS', 'Somali Shilling', 'Sh', 'Somalia'),
('SRD', 'Surinam Dollar', '$', 'Suriname'),
('SSP', 'South Sudanese Pound', '£', 'South Sudan'),
('STN', 'Dobra', 'Db', 'São Tomé and Príncipe'),
('SYP', 'Syrian Pound', '£', 'Syria'),
('SZL', 'Lilangeni', 'L', 'Eswatini'),
('THB', 'Baht', '฿', 'Thailand'),
('TJS', 'Somoni', 'ЅМ', 'Tajikistan'),
('TMT', 'Turkmenistan New Manat', 'm', 'Turkmenistan'),
('TND', 'Tunisian Dinar', 'د.ت', 'Tunisia'),
('TOP', 'Pa''anga', 'T$', 'Tonga'),
('TRY', 'Turkish Lira', '₺', 'Türkiye'),
('TTD', 'Trinidad and Tobago Dollar', 'TT$', 'Trinidad and Tobago'),
('TWD', 'New Taiwan Dollar', 'NT$', 'Taiwan'),
('TZS', 'Tanzanian Shilling', 'TSh', 'Tanzania'),
('UAH', 'Hryvnia', '₴', 'Ukraine'),
('UGX', 'Uganda Shilling', 'USh', 'Uganda'),
('USD', 'US Dollar', '$', 'United States'),
('UYU', 'Peso Uruguayo', '$U', 'Uruguay'),
('UZS', 'Uzbekistan Sum', 'so''m', 'Uzbekistan'),
('VES', 'Bolivar Soberano', 'Bs.S', 'Venezuela'),
('VND', 'Dong', '₫', 'Vietnam'),
('VUV', 'Vatu', 'VT', 'Vanuatu'),
('WST', 'Tala', 'T', 'Samoa'),
('XAF', 'CFA Franc BEAC', 'FCFA', 'Central Africa (CEMAC)'),
('XCD', 'East Caribbean Dollar', '$', 'Eastern Caribbean'),
('XOF', 'CFA Franc BCEAO', 'CFA', 'West Africa (UEMOA)'),
('XPF', 'CFP Franc', '₣', 'French Pacific Territories'),
('YER', 'Yemeni Rial', '﷼', 'Yemen'),
('ZAR', 'Rand', 'R', 'South Africa'),
('ZMW', 'Zambian Kwacha', 'ZK', 'Zambia'),
('ZWL', 'Zimbabwe Dollar', '$', 'Zimbabwe');
